name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'maven'

      - name: Check code style
        run: mvn checkstyle:check

      - name: Build and run tests
        run: mvn clean verify

      - name: Upload test reports
        uses: actions/upload-artifact@v5
        if: success() || failure()
        with:
          name: test-reports
          path: |
            target/surefire-reports/
            target/failsafe-reports/
            target/checkstyle-result.xml